CC=gcc
CFLAGS=

tcp_client: tcp_client.c
	gcc -o tcp_client tcp_client.c

tcp_server: tcp_server.c
	gcc -o tcp_server tcp_server.c

server: server.c
	gcc -o server server.c

all: tcp_client tcp_server server
